name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: BlackoutScanner.sln                        # Your actual solution file
      Project_Path: BlackoutScanner\BlackoutScanner.csproj      # Path to your project file

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore $env:Solution_Name

    # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution (if you have any)
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build --verbosity normal
      env:
        Configuration: ${{ matrix.configuration }}
      continue-on-error: true  # Continue even if no tests exist

    # Publish the application
    - name: Publish the application
      run: dotnet publish $env:Project_Path -c $env:Configuration -o publish\${{ matrix.configuration }} --self-contained true -r win-x64
      env:
        Configuration: ${{ matrix.configuration }}

    # Copy tessdata folder to publish directory (needed for OCR)
    - name: Copy tessdata to publish directory
      run: |
        if (Test-Path "BlackoutScanner\tessdata") {
          Copy-Item -Path "BlackoutScanner\tessdata" -Destination "publish\${{ matrix.configuration }}\tessdata" -Recurse -Force
          Write-Host "Copied tessdata folder to publish directory"
        } else {
          Write-Host "tessdata folder not found in repository"
        }
      shell: pwsh

    # Upload the build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BlackoutScanner-${{ matrix.configuration }}-${{ github.sha }}
        path: publish\${{ matrix.configuration }}\*
        retention-days: 30

    # Create a release zip (only for Release configuration)
    - name: Create Release Archive
      if: matrix.configuration == 'Release'
      run: |
        Compress-Archive -Path publish\Release\* -DestinationPath BlackoutScanner-Release.zip
      shell: pwsh

    # Upload release zip as artifact
    - name: Upload Release Archive
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: BlackoutScanner-Release-Archive
        path: BlackoutScanner-Release.zip
        retention-days: 30