name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.0.4, etc.
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]  # Trigger when a release is created

permissions:
  contents: write  # Need write permission to upload release assets

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: BlackoutScanner.sln                        # Your actual solution file
      Project_Path: BlackoutScanner\BlackoutScanner.csproj      # Path to your project file

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore $env:Solution_Name

    # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all unit tests in the solution (if you have any)
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build --verbosity normal
      env:
        Configuration: ${{ matrix.configuration }}
      continue-on-error: true  # Continue even if no tests exist

    # Publish the application
    - name: Publish the application
      run: dotnet publish $env:Project_Path -c $env:Configuration -o publish\${{ matrix.configuration }} --self-contained true -r win-x64
      env:
        Configuration: ${{ matrix.configuration }}

    # Copy tessdata folder to publish directory (needed for OCR)
    - name: Copy tessdata to publish directory
      run: |
        if (Test-Path "BlackoutScanner\tessdata") {
          Copy-Item -Path "BlackoutScanner\tessdata" -Destination "publish\${{ matrix.configuration }}\tessdata" -Recurse -Force
          Write-Host "Copied tessdata folder to publish directory"
        } else {
          Write-Host "tessdata folder not found in repository"
        }
      shell: pwsh

    # Create a release zip
    - name: Create Release Archive
      run: |
        $zipName = "BlackoutScanner-${{ matrix.configuration }}-x64.zip"
        Compress-Archive -Path publish\${{ matrix.configuration }}\* -DestinationPath $zipName
        Write-Host "Created archive: $zipName"
      shell: pwsh

    # Upload the build artifacts (for workflow artifacts)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BlackoutScanner-${{ matrix.configuration }}-${{ github.sha }}
        path: BlackoutScanner-${{ matrix.configuration }}-x64.zip
        retention-days: 30

    # Debug: Check event details
    - name: Debug Event Info
      run: |
        Write-Host "Event Name: ${{ github.event_name }}"
        Write-Host "Ref: ${{ github.ref }}"
        Write-Host "Ref Name: ${{ github.ref_name }}"
        Write-Host "Is Tag: ${{ startsWith(github.ref, 'refs/tags/') }}"
        Write-Host "Release Tag: ${{ github.event.release.tag_name }}"
      shell: pwsh

    # Upload Release Assets to GitHub Release (only on release/tag)
    - name: Upload Release Asset
      if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: BlackoutScanner-${{ matrix.configuration }}-x64.zip
        tag_name: ${{ github.event.release.tag_name || github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}